### ISSUE TITLE
Reserved keyword used in traits --> id with track call

### ISSUE THREAD

**Issue by nikospapcom** [rudderlabs/rudder-analytics-next#6]
Hey

I'm following `sample-next-app-npm` example and I'm getting the following error in console:
`Warning! : Reserved keyword used in traits --> id with track call`

Can you provide me a way to fix it?

**Comment by bardisg** [comment]
Hello @nikospapcom,

When setting custom properties object in [track](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api/#track) calls it is suggested you do not override the values of the reserved keys:
  'anonymous_id',
  'id',
  'sent_at',
  'received_at',
  'timestamp',
  'original_timestamp',
  'event_text',
  'event',
